version: '3.8'
services:
  server:
    build: ./server
    image: travtran/capstone-project-3900:server
    container_name: server_c
    ports:
      - '5001:5001'
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    build: ./client
    image: travtran/capstone-project-3900:client
    container_name: client_c
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    tty: true
