name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build Docker images with docker-compose
      run: docker-compose build
    - name: Push docker images to Docker Hub
      run: |
        docker push travtran/capstone-project-3900:server
        docker push travtran/capstone-project-3900:client
      

    
